[package]
name = "serialwriter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
command = "0.0.0"
serialport = "4.2.0"
sysinfo = "0.26.7"
